//LOGIN consts
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
//REGISTER consts
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
//ERROR consts
export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
//AUTH consts
export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
//SERVICE consts
export const SERVICE_CREATED = "SERVICE_CREATED";
export const SERVICE_SCHEDULED = "SERVICE_SCHEDULED";
export const SERVICE_ERRORS = "SERVICE_ERRORS";